### ISSUE TITLE
Ignore empty group_id

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audfactory#25]
With `group_id=''` we get a malformed URL:

```python
audfactory.url(
    'https://host',
    group_id='',
    name='name',
    repository='repo',
    version='1.0.0',
)
```
```
https://host/repo//name/1.0.0
```

I guess it's better if we ignore `group_id` in that case.

**Comment by hagenw** [comment]
It's not directly malformed, but it might be that some programs cannot work with it.

**Comment by hagenw** [comment]
I agree, that we should change it.

**Comment by hagenw** [comment]
The same happens for `name`, `repo`.

For `version` it would add an `/` at the end, which would not happen otherwise.

**Comment by hagenw** [comment]
On the other hand you could also argue that it is a feature not a bug that `group_id` returns something different than `group_id=None`.

**Comment by frankenjoe** [comment]
I encountered the problem in `audbackend` at this line:

https://github.com/audeering/audbackend/blob/master/audbackend/core/artifactory.py#L41

when `audfactory.path_to_group_id(folder)` returns `''` if `folder` is empty. So if we don't fix this here, we have to fix it in `audbackend`. But maybe we do similar things in other projects, so to me it feels safer to fix it here. Unless there is a use-case where we want to create an URL that has `//` in the path. But I doubt there is one. At least with `Artifactory` it will not find the artifact in that case.

**Comment by hagenw** [comment]
OK, as Artifactory cannot cope with it, I would say we should fix it here.
