### ISSUE TITLE
Stuck in download loop

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audfactory#29]
When I try to download a specific file from our Artifactory server on my local computer, I get stuck in the following loop:

![image](https://user-images.githubusercontent.com/10383417/143049971-2109fade-24c4-4750-af17-af0bf028180c.png)

Basically, it reads 0 bytes from the file, which is an indication that there are no more bytes left to read, but the condition `src_size > dst_size` is still True.

`src_size` is:

```
>>> src_size / 1024 / 1024 / 1024
1.0912588462233543
```

but `dst_size` only:

```
>>> dst_size / 1024 / 1024 / 1024
1.0105332834646106
```

On disk the file has `1.1 GB (1,085,050,880 bytes)` and on Artifactory it says:

![image](https://user-images.githubusercontent.com/10383417/143049563-22a29caf-1744-4dcb-9516-a8104030f6d6.png)

I have the following versions installed:

* dohq-artifactory-0.7.742
* audfactory-1.0.6

**Comment by frankenjoe** [comment]
It seems to be a problem with Artifactory. Downloading the file with the browser also fails...

**Comment by hagenw** [comment]
Can you try to download it with `artifactory.rest_get_stream()`, compare https://github.com/devopshq/artifactory/blob/master/artifactory.py#L753-L766

But it seems indeed related to Artifactory if you can also not download from the browser.

**Comment by frankenjoe** [comment]
> Can you try to download it with `artifactory.rest_get_stream()`, compare https://github.com/devopshq/artifactory/blob/master/artifactory.py#L753-L766

Do you have some sample code how to use this function? Having a hard to figure out and can't find any documentation.

**Comment by hagenw** [comment]
This was caused by having a size limit on cache file for downloading on a slow connection, compare https://www.jfrog.com/jira/browse/RTFACT-16743

We increased the allowed caching size on the server, can you try to download again and check if it is working now?

**Comment by frankenjoe** [comment]
> We increased the allowed caching size on the server, can you try to download again and check if it is working now?

Great, this solved the issue.
