### ISSUE TITLE
Is current API ok?

### ISSUE THREAD

**Issue by hagenw** [audeering/audfactory#6]
The current master is the release candidate for version `1.0.0` of `audfactory`.
Would be nice to check if you agree with the currently proposed API.
To check you need to compile the documentation locally.

Here is a summary of all the changes compared to version 0.8.1:

* Removed all deprecated functions
* Removed `audfactory.config.ARTIFACTORY_ROOT` and add support for different Artifactory server locations
* Based all unit tests on the https://audeering.jfrog.io/artifactory server
* Based all docstring tests in `audfactory/core/api.py` on the https://audeering.jfrog.io/artifactory server
* Disabled all docstring tests in `audfactory/core/lookup.py` as we don't have public lookup tables at the moment (and I think it is not worth the effort to include that already in the 1.0.0 release)
* Most of the functions no require a full URL as input, but for the functions where it make more sense to stay with `group_id`, `name`, `version`, `repository` as arguments I added another `server` argument where you now have to specify the URL of your Artifactory server

**Comment by frankenjoe** [comment]
Unfortunately, I cound't figure out how get a user name and password for https://audeering.jfrog.io/artifactory, so I couldn't really test any code. But I have built  the documentation and I think it looks good! I only have few comments:

* Why `audfactory.server_url()` and not just `audfactory.url()`?

* Maybe do :mod`audfactory` here:

![image](https://user-images.githubusercontent.com/10383417/112512724-ec5a9380-8d93-11eb-96c7-24a8139bbb5a.png)

* Link to `is_semantic_version()` is not working:

![image](https://user-images.githubusercontent.com/10383417/112512581-cc2ad480-8d93-11eb-88c2-c2c18d2206d4.png)

**Comment by hagenw** [comment]
The good news is you accessed https://audeering.jfrog.io/artifactory already. Building the documentation is accessing the `data-public` repository which has anonymous access.

For the other one you need to add an additional entry to `~/.artifactory_python.cfg` and I will create a user account for you.
Not sure yet where we document this.

**Comment by hagenw** [comment]
I renamed `audfactory.server_url()` to `audfactory.url()` and took the opportunity to do the same with `audfactory.artifactory_path()`, `audfactory.deploy_artifact()` and `audfactory.download_artifact()`.

I didn't use `:mod:` in the README as the README should also look nice on Github.

I fixed the link to `audeer.is_semantic_version()`
