### ISSUE TITLE
Tests for Lookup can fail on MacOS

### ISSUE THREAD

**Issue by hagenw** [audeering/audfactory#8]
There might be andom failures when executing `tests/test_lookup.py` on MacOS.

This might be related to #5, but I'm not sure.

**Comment by hagenw** [comment]
Since I have opened this issue no test has failed under macOS, so I will close this for now.

**Comment by frankenjoe** [comment]
We could also think about removing the support for `Lookup` tables. Or do we still use it somewhere?
